#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" &>/dev/null && pwd -P)

GH_AR_VERSION=0.2
DATE_TYPE=

if [ -n "${GH_ACTIVITY_REPORT_DEBUG:-}" ]; then
    set -x
fi

date_detect() {
    if [ -z "${DATE_TYPE}" ]; then
        date --version > /dev/null 2>&1 && DATE_TYPE="GNU" || DATE_TYPE="BSD"
    fi
}

is_gnu_date() {
    date_detect
    if [ "${DATE_TYPE}" = "GNU" ]; then
        return 0
    else
        return 1
    fi
}

date_day() {
    if is_gnu_date; then
        date -d "${1} day" "+%Y-%m-%d"
    else
        date -v "${1}d" "+%Y-%m-%d"
    fi
}

msg() {
    echo >&2 -e "${1-}"
}

die() {
    local msg=$1
    local code=${2-1} # default exit status 1
    msg "$msg"
    exit "$code"
}

usage() {
    # shellcheck disable=SC1078
    die "gh-activity-report version ${GH_AR_VERSION}

  -f, --format       string             Output format: [comment|gh|link|markdown] (default \"gh\")
  -h, --help                            Show help
      --version                         Show version
  -l, --limit        number             Maximum number of results to fetch
      --owner        string             Filter on repository owner
  -R, --repo         [HOST/]OWNER/REPO  Specify search target
      --sort         string             Sort fetched results: {comments|created|interactions|reactions|reactions-+1|reactions--1|reactions-heart|reactions-smile|reactions-tada|reactions-thinking_face|updated} (default \"updated\")
      --state        string             Filter based on state: {open|closed}
  -w, --web                             Open the search query in the web browser

account filter: Default --auther @me, if not specified bellow
                Account filters can be specified multiple times.
                In that case, it becomes an OR condition
  --assignee         string             Filter by assignee
  --author           string             Filter by author
  --involves         string             Filter based on involvement of user
  --mentions         string             Filter based on user mentions
  --commenter        string             Filter based on comments by user
  --review-requested string             Filter based on comments by user
  --reviewed-by      string             Filter on user who reviewed

date range:
  -d, --days-ago     since(..until)     Specify the period to filter n days ago
      --since        yyyy-mm-dd         Start date to filter by date
      --until        yyyy-mm-dd         End date to filter by date

date filter:
  --created                             Filter based on created at date
  --closed                              Filter on closed at date
  --merged                              Filter on merged at date
  --updated                             Filter on last updated at date

pull_request filter:
  --draft                               Filter based on draft state
" "$1"
}

declare -a GH_OPTIONS
declare -a GH_PRS_OPTIONS
declare -a GH_ISSUES_OPTIONS
declare -a GH_BYPASS_OPTIONS

append_csv_param() {
    if [ -n "${1}" ]; then
        echo "${1},${2}"
    else
        echo "${2}"
    fi
}

parse_params() {
    # default values of variables set from params
    SINCE=
    UNTIL=
    AUTHOR=
    ASSIGNEE=
    INVOLVES=
    MENTIONS=
    COMMENTER=
    REVIEW_REQUESTED=
    REVIEWED_BY=
    PRS_DATE_FILTER="updated"
    ISSUES_DATE_FILTER="updated"
    LIMIT=
    OWNER=
    REPO=
    SORT="updated"
    STATE=
    SEARCH_SUBCOMMAND="issues"
    FORMAT=
    INPUT_BYPASS_OPTIONS=()

    while :; do
        case "${1-}" in
        --assignee )
            ASSIGNEE=$(append_csv_param "${ASSIGNEE}" "${2-}")
            shift ;;
        --author )
            AUTHOR=$(append_csv_param "${AUTHOR}" "${2-}")
            shift ;;
        --created )
            PRS_DATE_FILTER="created"
            ISSUES_DATE_FILTER="created"
            ;;
        --closed )
            PRS_DATE_FILTER="closed"
            ISSUES_DATE_FILTER="closed"
            ;;
        --commenter )
            COMMENTER=$(append_csv_param "${COMMENTER}" "${2-}")
            shift ;;
        --days-ago| -d )
            DAYS_AGO="${2-}"
            DAYS_AGO_SINCE="${DAYS_AGO%%..*}"
            DAYS_AGO_UNTIL_="${DAYS_AGO#"${DAYS_AGO_SINCE}"}"
            DAYS_AGO_UNTIL="${DAYS_AGO_UNTIL_##*..}"
            if [ -n "${DAYS_AGO_SINCE}" ]; then
                SINCE=$(date_day "-${DAYS_AGO_SINCE}")
            fi
            if [ -n "${DAYS_AGO_UNTIL}" ]; then
                UNTIL=$(date_day "-${DAYS_AGO_UNTIL}")
            fi
            shift ;;
        --draft )
            GH_PRS_OPTIONS+=(--draft)
            SEARCH_SUBCOMMAND="prs"
            ;;
        --format| -f )
            case "${2-}" in
            gh ) ;;
            * )
                FORMAT="${2-}"
                if [ ! -f "${SCRIPT_DIR}/format/${FORMAT}.template" ] \
                && [ ! -f "${SCRIPT_DIR}/format/issues/${FORMAT}.template" ]; then
                    echo "error: invalid format type"
                    usage 1
                fi
                ;;
            esac
            shift ;;
        --involves )
            INVOLVES=$(append_csv_param "${INVOLVES}" "${2-}")
            shift ;;
        --limit| -l )
            LIMIT="${2-}"
            shift ;;
        --mentions )
            MENTIONS=$(append_csv_param "${MENTIONS}" "${2-}")
            shift ;;
        --merged )
            GH_PRS_OPTIONS+=("--merged")
            PRS_DATE_FILTER="merged-at"
            SEARCH_SUBCOMMAND="prs"
            ;;
        --owner )
            OWNER="${2-}"
            shift ;;
        --repo| -R )
            REPO="${2-}"
            shift ;;
        --review-requested )
            REVIEW_REQUESTED=$(append_csv_param "${REVIEW_REQUESTED}" "${2-}")
            SEARCH_SUBCOMMAND="prs"
            shift ;;
        --reviewed-by )
            REVIEWED_BY=$(append_csv_param "${REVIEWED_BY}" "${2-}")
            SEARCH_SUBCOMMAND="prs"
            shift ;;
        --since )
            SINCE="${2-}"
            shift ;;
        --sort )
            SORT="${2-}"
            shift ;;
        --state )
            STATE="${2-}"
            shift ;;
        --until )
            UNTIL="${2-}"
            shift ;;
        --updated )
            PRS_DATE_FILTER="updated"
            ISSUES_DATE_FILTER="updated"
            ;;
        --web| -w )
            GH_OPTIONS+=(--web)
            ;;
        --version )
            echo "gh-activity-report version ${GH_AR_VERSION}"
            ;;
        --help| -h )
            usage 0
            ;;
        -- )
            shift
            INPUT_BYPASS_OPTIONS=("$@")
            break ;;
        --* )
            echo "${1:-} is invalid option."
            usage 1
            ;;
        *) break ;;
        esac
        shift
    done
    return 0
}

parse_params "$@"

if [ -n "${LIMIT}" ]; then
    GH_OPTIONS+=(--limit "${LIMIT}")
fi
if [ -n "${OWNER}" ]; then
    GH_OPTIONS+=(--owner "${OWNER}")
fi
if [ -n "${REPO}" ]; then
    GH_OPTIONS+=(--repo "${REPO}")
fi
if [ -n "${SORT}" ]; then
    GH_OPTIONS+=(--sort "${SORT}")
fi
if [ -n "${STATE}" ]; then
    GH_OPTIONS+=(--state "${STATE}")
fi

# date filter
DATE_QUERY=
if [ -n "${SINCE}" ]; then
    if [ -n "${UNTIL}" ]; then
        DATE_QUERY="${SINCE}..${UNTIL}"
    else
        DATE_QUERY=">=${SINCE}"
    fi
else
    if [ -n "${UNTIL}" ]; then
        DATE_QUERY="<=${UNTIL}"
    fi
fi
if [ -n "${DATE_QUERY}" ]; then
    GH_PRS_OPTIONS+=("--${PRS_DATE_FILTER}" "${DATE_QUERY}")
    GH_ISSUES_OPTIONS+=("--${ISSUES_DATE_FILTER}" "${DATE_QUERY}")
fi

# account filter
if [ -z "${AUTHOR}${ASSIGNEE}${INVOLVES}${MENTIONS}${COMMENTER}${REVIEW_REQUESTED}${REVIEWED_BY}" ]; then
    AUTHOR="@me"
fi

multi_option() {
    IFS="," read -r -a VARS <<< "${2}"
    for index in "${!VARS[@]}"; do
        if [ "${index}" == 0 ]; then
            GH_OPTIONS+=("${1}" "${VARS[${index}]}")
        else
            GH_BYPASS_OPTIONS+=("${3:-"${1#--}"}":"${VARS[${index}]}")
        fi
    done
}

if [ -n "${AUTHOR}" ]; then
    multi_option --author "${AUTHOR}"
fi
if [ -n "${ASSIGNEE}" ]; then
    multi_option --assignee "${ASSIGNEE}"
fi
if [ -n "${INVOLVES}" ]; then
    multi_option --involves "${INVOLVES}"
fi
if [ -n "${MENTIONS}" ]; then
    multi_option --mentions "${MENTIONS}"
fi
if [ -n "${COMMENTER}" ]; then
    multi_option --commenter "${COMMENTER}"
fi
if [ -n "${REVIEW_REQUESTED}" ]; then
    multi_option --review-requested "${REVIEW_REQUESTED}"
fi
if [ -n "${REVIEWED_BY}" ]; then
    multi_option --reviewed-by "${REVIEWED_BY}"
fi

get_format_template() {
    FORMAT_TEMPLATE=$(cat "${1}/${FORMAT}.template")
    JSON_KEYS=$(cat "${1}/${FORMAT}.keys")
    GH_OPTIONS+=(--json "${JSON_KEYS}")
    GH_OPTIONS+=(--template "${FORMAT_TEMPLATE}")
}
    
if [ -n "${FORMAT}" ]; then
    if [ -f "${SCRIPT_DIR}/format/${FORMAT}.template" ]; then
        get_format_template "${SCRIPT_DIR}/format"
    else
        get_format_template "${SCRIPT_DIR}/format/${SEARCH_SUBCOMMAND}"
    fi    
fi

is_contains() {
    match="${1}"
    shift
    while [ -n "${1}" ]; do
        [[ "${match}" == "${1}" ]] && return 0
        shift
    done
    return 1
}

if [ "${#GH_BYPASS_OPTIONS[@]}" != 0 ]; then
    is_contains "--" "${INPUT_BYPASS_OPTIONS[@]}" "" || INPUT_BYPASS_OPTIONS+=(--)
fi

search() {
    if [ "${SEARCH_SUBCOMMAND}" = "prs" ]; then
        gh search prs "${GH_OPTIONS[@]}" "${GH_PRS_OPTIONS[@]}" "${INPUT_BYPASS_OPTIONS[@]}" "${GH_BYPASS_OPTIONS[@]}"
    else
        gh search issues --include-prs "${GH_OPTIONS[@]}" "${GH_ISSUES_OPTIONS[@]}" "${INPUT_BYPASS_OPTIONS[@]}"  "${GH_BYPASS_OPTIONS[@]}"
    fi
}

search
