#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" &>/dev/null && pwd -P)

GH_AR_VERSION=0.1
DATE_TYPE=

date_detect() {
    if [ -z "${DATE_TYPE}" ]; then
        date --version > /dev/null 2>&1 && DATE_TYPE="GNU" || DATE_TYPE="BSD"
    fi
}

is_gnu_date() {
    date_detect
    if [ "${DATE_TYPE}" = "GNU" ]; then
        return 0
    else
        return 1
    fi
}

date_day() {
    if is_gnu_date; then
        date -d "${1} day" "+%Y-%m-%d"
    else
        date -v "${1}d" "+%Y-%m-%d"
    fi
}

msg() {
    echo >&2 -e "${1-}"
}

die() {
    local msg=$1
    local code=${2-1} # default exit status 1
    msg "$msg"
    exit "$code"
}

usage() {
    die "gh-activity-report version ${GH_AR_VERSION}"
}

parse_params() {
    # default values of variables set from params
    SINCE=
    UNTIL=
    AUTHOR=
    ASSIGNEE=
    INVOLVES=
    MENTIONS=
    COMMENTER=
    PRS_DATE_FILTER=updated
    ISSUES_DATE_FILTER=updated
    REPO=

    while :; do
        case "${1-}" in
        --assignee)
            ASSIGNEE="${2-}"
            shift ;;
        --author)
            AUTHOR="${2-}"
            shift ;;
        --created )
            PRS_DATE_FILTER=created
            ISSUES_DATE_FILTER=created
            ;;
        --closed )
            PRS_DATE_FILTER=closed
            ISSUES_DATE_FILTER=closed
            ;;
        --commenter)
            COMMENTER="${2-}"
            shift ;;
        --days-ago| -d )
            DAYS_AGO="${2-}"
            SINCE=$(date_day "-${2-}")
            shift ;;
        --involves)
            INVOLVES="${2-}"
            shift ;;
        --mentions)
            MENTIONS="${2-}"
            shift ;;
        --merged )
            PRS_DATE_FILTER=merged
            ISSUES_DATE_FILTER=closed
            ;;
        --repo| -R )
            REPO="${2-}"
            shift ;;
        --since )
            SINCE="${2-}"
            shift ;;
        --until )
            UNTIL="${2-}"
            shift ;;
        --updated )
            PRS_DATE_FILTER=updated
            ISSUES_DATE_FILTER=updated
            ;;
        --version )
            echo "gh-activity-report version ${GH_AR_VERSION}"
            ;;
        --)
            shift
            BYPASS_OPTIONS=($@)
            break ;;
        *) break ;;
        esac
        shift
    done
    return 0
}

parse_params "$@"

declare -a GH_OPTIONS
declare -a GH_PRS_OPTIONS
declare -a GH_ISSUES_OPTIONS

if [ -n "${REPO}" ]; then
    GH_OPTIONS+=(--repo "${REPO}")
fi

# date filter
DATE_QUERY=
if [ -n "${SINCE}" ]; then
    if [ -n "${UNTIL}" ]; then
        DATE_QUERY="${SINCE}..${UNTIL}"
    else
        DATE_QUERY=">=${SINCE}"
    fi
else
    if [ -n "${UNTIL}" ]; then
        DATE_QUERY="<=${UNTIL}"
    fi
fi
if [ -n "${DATE_QUERY}" ]; then
    GH_PRS_OPTIONS+=(--${PRS_DATE_FILTER} "${DATE_QUERY}")
    GH_ISSUES_OPTIONS+=(--${ISSUES_DATE_FILTER} "${DATE_QUERY}")
fi

# account filter
if [ -z "${AUTHOR}${ASSIGNEE}${INVOLVES}${MENTIONS}${COMMENTER}" ]; then
    AUTHOR="@me"
fi
if [ -n "${AUTHOR}" ]; then
    GH_OPTIONS+=(--author "${AUTHOR}")
fi
if [ -n "${ASSIGNEE}" ]; then
    GH_OPTIONS+=(--assignee "${ASSIGNEE}")
fi
if [ -n "${INVOLVES}" ]; then
    GH_OPTIONS+=(--involves "${INVOLVES}")
fi
if [ -n "${MENTIONS}" ]; then
    GH_OPTIONS+=(--mentions "${MENTIONS}")
fi
if [ -n "${COMMENTER}" ]; then
    GH_OPTIONS+=(--commenter "${COMMENTER}")
fi

gh search prs "${GH_OPTIONS[@]}" "${GH_PRS_OPTIONS[@]}" "${BYPASS_OPTIONS[@]}"
gh search issues "${GH_OPTIONS[@]}" "${GH_ISSUES_OPTIONS[@]}" "${BYPASS_OPTIONS[@]}"
